{
 "title": "TON",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(ton_unixtime, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Election Ends",
   "type": "singlestat",
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ton_election_active_id{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Validator Election Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ton_validator_election_date{instance=\"$instance\"}) * 1000"
    }
   ]
  },
  {
   "title": "Validator Key Expiration Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(ton_validator_expire_at{instance=\"$instance\"}) * 1000"
    }
   ]
  },
  {
   "title": "Non-Expired Validators On Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (instance) (ton_validator_election_date{instance=\"$instance\"} <= on(instance) group_left() ton_election_active_id{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current Validator Election Date",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max without (index) (clamp_max(ton_validator_election_date{instance=\"$instance\"}, 1))",
     "legendFormat": "{{ adnl_addr }}"
    },
    {
     "expr": "clamp_max(ton_election_active_id{instance=\"$instance\"}, 1)",
     "legendFormat": "Election"
    }
   ]
  },
  {
   "title": "Shard Block Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ton_shard_height{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ shard_id }}"
    }
   ]
  },
  {
   "title": "Validator Set",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ton_validator_is_active{instance=\"$instance\"} == 1",
     "legendFormat": "ACTIVE: {{ adnl_addr }}"
    },
    {
     "expr": "ton_validator_is_next{instance=\"$instance\"} == 1",
     "legendFormat": "NEXT: {{ adnl_addr }}"
    }
   ]
  },
  {
   "title": "Current Validator Election Date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "ton_validator_election_date{instance=\"$instance\"} * 1000",
     "legendFormat": "{{ adnl_addr }}"
    },
    {
     "expr": "ton_election_active_id{instance=\"$instance\"} * 1000",
     "legendFormat": "Election"
    }
   ]
  },
  {
   "title": "Validator Work Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ton_validator_stats_mc_total{instance=\"$instance\"}[15m])",
     "legendFormat": "Masterchain Work"
    },
    {
     "expr": "rate(ton_validator_stats_shard_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Shardchain Work"
    }
   ]
  },
  {
   "title": "Masterchain Blocks per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ton_shardclientmasterchainseqno{instance=\"$instance\"}[5m])",
     "legendFormat": "Shard Client Masterchain"
    },
    {
     "expr": "rate(ton_stateserializermasterchainseqno{instance=\"$instance\"}[5m])",
     "legendFormat": "Serializer Masterchain"
    }
   ]
  },
  {
   "title": "Validator Work Rate (Detail)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ton_validator_stats_mc_cnt2048{instance=\"$instance\"}[15m])",
     "legendFormat": "Masterchain cnt2048"
    },
    {
     "expr": "rate(ton_validator_stats_mc_cnt65536{instance=\"$instance\"}[5m])",
     "legendFormat": "Masterchain cnt65536"
    },
    {
     "expr": "rate(ton_validator_stats_shard_cnt2048{instance=\"$instance\"}[5m])",
     "legendFormat": "Shardchain cnt2048"
    },
    {
     "expr": "rate(ton_validator_stats_shard_cnt65536{instance=\"$instance\"}[5m])",
     "legendFormat": "Shardchain cnt65536"
    }
   ]
  },
  {
   "title": "Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ton_unixtime{instance=\"$instance\"}[1m])",
     "legendFormat": "ton_unixtime"
    },
    {
     "expr": "rate(ton_masterchainblocktime{instance=\"$instance\"}[1m])",
     "legendFormat": "ton_masterchainblocktime"
    }
   ]
  },
  {
   "title": "Active Validator Weight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ton_validator_active_weight{instance=\"$instance\"}",
     "legendFormat": "{{ adnl_addr }}"
    }
   ]
  }
 ]
}